### PR TITLE
Fixes #8 - git repo initialization

### LINKED ISSUE #8: Rugged::RepositoryError: could not find repository from '/wiki'
I've tried to fire up Gollum with this new official Docker release with this barebone docker-compose file I wrote based on the info available [here](https://github.com/gollum/gollum/wiki/Gollum-via-Docker), however after initialization I was presented with the error `Rugged::RepositoryError could not find repository from '/wiki'`

```yml
version: "3.7"

services:
  gollum:
    image: gollumorg/gollum:5.1
    container_name: gollum
    restart: always
    ports:
      - 890:8080
#    volumes:
#      - ./config.rb:/etc/gollum/config.rb
#      - wikidata:/wiki
    command:
      - "--port=8080"
#      - "--config=/etc/gollum/config.rb"
#volumes:
# wikidata:
```
After inspecting the running container with `docker exec` I found that the git repository in the /wiki direcotry hasn't been initialized, after issuing `git init` inside `/wiki` Gollum worked perfectly fine.

Indeed, in the [Dockerfile ](https://github.com/gollum/docker/blob/master/Dockerfile)used there is no initialization of the repository.

### PR DESCRIPTION
**Pull request by maxiride**
The git repo wasn't initialized, see: https://github.com/gollum/gollum/wiki/Gollum-via-Docker#preparing-the-gollum-workspace

This PR addresses #8 

I usually would't PR over the master branch but there is no development branch I could have used sorry.

### CODE REVIEW

**Comment by dometto** [comment]
Thanks for chipping in @maxiride! I guess there is a question whether this is necessary/wanted by default: what if I want to run gollum with an existing git repository on the host machine, by exposing it to the container? Both that, and your approach of initializing on container run, seem sensible patterns. @scolytus @fanhongtao you weigh in on this? what would the most typical way of using gollum with docker be?

**Comment by maxiride** [comment]
I almost forgot about this PR 😄

> what if I want to run gollum with an existing git repository on the host machine, by exposing it to the container? 

The user should use a volume binding either with the docker `-v` option or in the `docker-compose.yml` configuration file, mounting in the container the user defined directory with a pre-existing initialized repo. The container original `/wiki` directory would be shadowed with no conflicts.

This approach is utilized in many major docker images like Postgres\MySQL, an image should be "self-sufficient" with the option to use custom settings and directories with the proper volume bindings.

**Comment by razem-io** [comment]
Just stumbled upon this because I had the same expectation, that the image would just run if not configured. If you want to use your own git repository just mount it. It won't have a issue with this implementation. 

One could argue that a custom entrypoint might be better to keep the size down but in this case it is a bit of an overkill.

**Comment by dometto** [comment]
@scolytus I've merged this PR since it seems to make sense. Can you explain what the current workflow is for getting this published on DockerHub? Does this work automagically yet?

**Pull request merged**
